_name_: s4d_mf
d_state: 64
channels: 1
bidirectional: false
activation: gelu
postact: null
dropout: ${..dropout} # Same as null

rho: 0.9
dt: 0.01
eigvals_name: conjugate_linear
n_conjugate: 2

# dt_min: 0.001
# dt_max: 0.1
lr: 0.001
n_ssm: 1
